import 'package:flutter/material.dart';
import 'package:get/get.dart';

import '../controllers/privacy_policy_controller.dart';

class PrivacyPolicyView extends GetView<PrivacyPolicyController> {
  const PrivacyPolicyView({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF9F9F9),
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios, color: Colors.black87),
          onPressed: () => Get.back(),
        ),
        centerTitle: true,
        title: const Text(
          "Privacy policy",
          style: TextStyle(
            color: Color(0xFF1C1C1E),
            fontSize: 22,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),

      body: SingleChildScrollView(
        padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 10),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [

            _title("Stylor.ai — Privacy Policy"),
            _space(),

            _subTitle("Last Updated: December 2025"),
            _space(),

            _body(
              'This Privacy Policy explains how Stylor.ai ("we", "our", or "us") '
                  'collects, uses, and protects your information when you use our '
                  'mobile application and related services.',
            ),

            _section("1. Information We Collect"),
            _body("We collect the following types of information:"),
            _subSection("1.1 Account Information"),
            _bulletList([
              "Name",
              "Email address",
              "Password",
            ]),

            _subSection("1.2 Personal Preferences for Outfit Generation"),
            _bulletList([
              "Date of birth",
              "Gender",
              "Location (approximate)",
              "Style preferences",
              "Color preferences",
              "Body type",
              "Skin tone",
              "Season preferences",
            ]),

            _subSection("1.3 Usage Information"),
            _bulletList([
              "Outfits you like or skip",
              "Filters you select",
              "Items you add to favorites or cart",
              "Interaction data within the app",
            ]),

            _subSection("1.4 Images You Upload"),
            _bulletList([
              "Wardrobe images you upload",
              "Background-removed versions generated by the app",
            ]),

            _subSection("1.5 Device Information"),
            _bulletList([
              "Device type",
              "Operating system",
              "App version",
            ]),

            _section("2. How We Use Your Information"),
            _bulletList([
              "Generate AI-based outfit suggestions",
              "Personalize your experience",
              "Show similar products and recommendations",
              "Improve app performance",
              "Provide customer support",
              "Send optional notifications (reminders)",
            ]),

            _section("3. Affiliate Links"),
            _body(
              "Stylor.ai provides product suggestions through affiliate partners. "
                  "When you click Buy Now, you may be redirected to a partner website. "
                  "If you make a purchase, we may earn a commission.\n\n"
                  "We do not receive your payment information. All purchases are handled by the retailer you visit.",
            ),

            _section("4. Image Processing"),
            _body(
              "Wardrobe photos you upload are used only to:\n\n"
                  "• Remove background\n"
                  "• Show clean wardrobe previews\n"
                  "• Suggest similar products\n\n"
                  "We do not use your wardrobe photos for training our AI models.",
            ),

            _section("5. Data Sharing"),
            _body(
              "We do not sell your personal information. We may share limited data with:\n\n"
                  "• Affiliate partners (only click-tracking)\n"
                  "• Service providers that help operate the app (analytics, hosting)",
            ),

            _section("6. Data Protection"),
            _body(
              "We take reasonable security measures to protect your data "
                  "from unauthorized access or misuse.",
            ),

            _section("7. Your Choices"),
            _bulletList([
              "Update your preferences anytime",
              "Turn notifications on or off",
              "Delete your account",
              "Request your data to be deleted",
            ]),
            _body("To request account or data deletion, contact us at: stylorai.123@gmail.com"),

            _section("8. Children’s Privacy"),
            _body(
              "Our app is not intended for users under 13. "
                  "We do not knowingly collect information from children.",
            ),

            _section("9. Changes to This Policy"),
            _body(
              "We may update this Privacy Policy. If changes are significant, "
                  "you will be notified in the app.",
            ),

            _section("10. Contact Us"),
            _body(
              "If you have questions about this Privacy Policy, contact: "
                  "stylorai.123@gmail.com",
            ),

            const SizedBox(height: 50),
          ],
        ),
      ),
    );
  }

  // ------- UI HELPERS BELOW -------

  Widget _title(String text) => Text(
    text,
    style: const TextStyle(
      fontSize: 20,
      fontWeight: FontWeight.w700,
      color: Color(0xFF060017),
    ),
  );

  Widget _subTitle(String text) => Text(
    text,
    style: const TextStyle(
      fontSize: 16,
      fontWeight: FontWeight.w500,
      color: Color(0xFF060017),
    ),
  );

  Widget _section(String text) => Padding(
    padding: const EdgeInsets.only(top: 20, bottom: 6),
    child: Text(
      text,
      style: const TextStyle(
        fontSize: 18,
        fontWeight: FontWeight.w600,
        color: Color(0xFF060017),
      ),
    ),
  );

  Widget _subSection(String text) => Padding(
    padding: const EdgeInsets.only(top: 14, bottom: 6),
    child: Text(
      text,
      style: const TextStyle(
        fontSize: 16,
        fontWeight: FontWeight.w500,
        color: Color(0xFF060017),
      ),
    ),
  );

  Widget _body(String text) => Text(
    text,
    style: const TextStyle(
      fontSize: 14,
      height: 1.55,
      color: Color(0xFF49494B),
    ),
  );

  Widget _bulletList(List<String> items) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: items.map((e) {
        return Padding(
          padding: const EdgeInsets.only(bottom: 6),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text("•  ", style: TextStyle(fontSize: 16)),
              Expanded(
                child: Text(
                  e,
                  style: const TextStyle(
                    fontSize: 14,
                    height: 1.55,
                    color: Color(0xFF49494B),
                  ),
                ),
              ),
            ],
          ),
        );
      }).toList(),
    );
  }

  Widget _space() => const SizedBox(height: 10);
}
